version: '3.4'

services:
  db:
    image: postgres
    restart: always
    env_file: .env
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    ports:
      - 8000:8000
    depends_on: 
      - db
    volumes: 
      - .:/app     
  rabbitmq:
    image: rabbitmq:3.8-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  celery:
    build: .
    env_file: .env
    command: celery -A C2D worker -l info
    volumes: 
      - .:/app
  celery-beat:
    build: .
    env_file: .env
    command: celery -A C2D beat -l info