# Generated by Django 3.0.8 on 2020-09-27 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('important_background', models.TextField(max_length=400)),
                ('allergies', models.CharField(max_length=254)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_observations', models.CharField(blank=True, max_length=254, null=True)),
                ('family_background', models.TextField(max_length=400)),
                ('pathological_background', models.CharField(max_length=250)),
                ('currently_medication', models.CharField(blank=True, max_length=250, null=True)),
                ('surgeries', models.CharField(blank=True, max_length=250, null=True)),
                ('nonpath_background', models.CharField(max_length=250)),
                ('smoking', models.BooleanField(blank=True, null=True)),
                ('drinking', models.BooleanField(blank=True, null=True)),
                ('gynecological_background', models.CharField(blank=True, max_length=250, null=True)),
                ('system_interrogation', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
            options={
                'db_table': 'Medical Records',
            },
        ),
    ]
