# Generated by Django 3.0.8 on 2020-09-28 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_cita_exp'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaExpress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_reason', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
    ]
