# Generated by Django 3.0.8 on 2020-09-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_express', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaexpress',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
