# Generated by Django 3.0.8 on 2020-08-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='hora',
        ),
        migrations.AddField(
            model_name='cita',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
