# Generated by Django 3.0.8 on 2020-09-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_auto_20200911_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='room',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
