# Generated by Django 3.0.8 on 2020-09-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cita_exp',
            field=models.BooleanField(default=False),
        ),
    ]
