# Generated by Django 3.0.8 on 2020-09-29 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_cita_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='cita_exp',
        ),
    ]
