# Generated by Django 3.0.8 on 2020-09-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TWTestToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TWTokenTest',
            },
        ),
    ]
