# Generated by Django 3.0.8 on 2020-09-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20200927_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twtesttoken',
            name='token',
            field=models.TextField(max_length=500),
        ),
    ]
