# Generated by Django 3.0.8 on 2020-09-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20200927_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='twtesttoken',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
