# Generated by Django 3.0.8 on 2020-09-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_twtesttoken_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twtesttoken',
            name='status',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
