# Generated by Django 3.0.8 on 2020-09-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20200928_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twtesttoken',
            name='status',
            field=models.BooleanField(default=True, max_length=50),
        ),
    ]
