# Generated by Django 3.0.8 on 2020-08-03 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=18, verbose_name='CFCI')),
                ('fiscal_address', models.CharField(max_length=50, verbose_name='Fiscal address')),
                ('rfc', models.CharField(max_length=15, verbose_name='RFC')),
                ('cfdi', models.CharField(max_length=50, verbose_name='CFDI')),
                ('university', models.CharField(max_length=150, verbose_name='Universidad')),
                ('professional_license', models.CharField(max_length=15, verbose_name='Professional license')),
                ('speciality', models.CharField(max_length=100, verbose_name='Speciality')),
                ('postgraduate', models.CharField(max_length=100, verbose_name='Postgraduate')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('contact_phone', models.CharField(max_length=13, verbose_name='Contact phone')),
                ('reference', models.CharField(max_length=50, verbose_name='Reference')),
                ('name_account_owner', models.CharField(max_length=75, verbose_name='Name account owner')),
                ('bank', models.CharField(max_length=75, verbose_name='Bank')),
                ('account', models.CharField(max_length=20, verbose_name='Account')),
                ('clabe', models.CharField(max_length=18, verbose_name='CLABE')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctors',
                'ordering': ['speciality'],
            },
        ),
    ]
