# Generated by Django 3.0.8 on 2020-10-08 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=2020)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor')),
            ],
            options={
                'db_table': 'Schedule',
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctors.Schedule')),
            ],
            options={
                'db_table': 'Hours',
                'ordering': ['hour'],
            },
        ),
    ]
