# Generated by Django 3.0.8 on 2020-10-08 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_hour_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='hour1',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='hour2',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='hour3',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='hour4',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='hour5',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='hour6',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='hour7',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='hour9',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor'),
        ),
        migrations.DeleteModel(
            name='Hour',
        ),
    ]
