# Generated by Django 3.0.8 on 2020-10-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20201008_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(error_messages={'unique': 'Day already created'}, max_length=50, unique=True),
        ),
    ]
